version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=smartolt_alternative
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - gns3_net
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartolt_alternative
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - gns3_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    networks:
      - gns3_net

networks:
  gns3_net:
    external: true
